---


###
# Debug, list what we can find

- name: Show contents of "{{zuul.executor.work_root }}"
  find:
    paths: "{{zuul.executor.work_root }}"
    file_type: directory
    recurse: yes
  register: find_results
  delegate_to: localhost

- debug:
    var: find_results


####
- name: Show contents of "{{zuul.executor.work_root }}/{{ zuul.project.src_dir }}"
  find:
    paths: "{{zuul.executor.work_root }}/{{ zuul.project.src_dir }}"
    file_type: any
    recurse: yes
  register: find_results

- debug:
    var: find_results


###
# Copy files from local checkout on top of Ansible checkout
# This is only needed till ansible-test is updated

- name: Create modules/galaxy
  file:
    path: "{{ ansible_path }}/lib/ansible/modules/galaxy/"
    state: directory

- name: Copy modules
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_path }}/lib/ansible/modules/galaxy/"
  with_fileglob:
    - " {{zuul.executor.work_root }}/{{ zuul.project.src_dir }}/library/*"
  ignore_errors: yes

- name: Show contents of "{{ ansible_path }}/lib/ansible/modules/"
  find:
    paths: " {{ ansible_path }}/lib/ansible/modules/"
    file_type: directory
    recurse: yes
  register: find_results

- debug:
    var: find_results

###
# Run ansible-test
#

- name: Run ansible-test
  command: "{{ ansible_path }}/test/runner/ansible-test sanity --requirements --python {{ python_version }} --tox lib/ansible/modules/galaxy"
