---


###
# Debug, list what we can find

#- debug:
#    var: hostvars


# "{ ansible_user_dir }}/{{ zuul.project.src_dir }}" =  /home/zuul-worker/src/github.com/ansible-network/network-engine
# "{{ ansible_path }}/test/runner/ansible-test"

####
- name: Show contents of "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
  find:
    paths: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
    file_type: directory
    recurse: yes


###
# Copy files from local checkout on top of Ansible checkout
# This is only needed till ansible-test is updated


- name: Create modules/galaxy
  file:
    path: "{{ ansible_user_dir }}/{{ ansible_path }}/lib/ansible/modules/galaxy/"
    state: directory
  register: foo

- name: Create modules/galaxy/__init__.py
  file:
    path: "{{ ansible_user_dir }}/{{ ansible_path }}/lib/ansible/modules/galaxy/__init__.py"
    state: touch

- name: copy modules
  shell: "cp {{ ansible_user_dir }}/{{ zuul.project.src_dir }}/library/* {{ ansible_path }}/lib/ansible/modules/galaxy/"
  ignore_errors: yes
  register: foo

- name: copy action_plugin
  shell: "cp {{ ansible_user_dir }}/{{ zuul.project.src_dir }}/action_plugins/* {{ ansible_path }}/lib/ansible/plugins/action/"
  ignore_errors: yes
  register: foo

# WITH_ITEMS the above src & directories

- debug:
    var: foo

- name: Show contents of "{{ ansible_user_dir }}/{{ ansible_path }}/lib/ansible/modules/galaxy/"
  find:
    paths: "{{ ansible_user_dir }}/{{ ansible_path }}/lib/ansible/modules/galaxy"
    file_type: any
    recurse: yes
  register: find_results

- debug:
    var: find_results

###
# Run ansible-test
#

- name: Run ansible-test
  command: "{{ ansible_path }}/test/runner/ansible-test sanity --requirements --python {{ python_version }} --tox lib/ansible/modules/galaxy/ /lib/ansible/plugins/action/"

