---


###
# Debug, list what we can find

- debug:
    var: hostvars

# "{ ansible_user_dir }}/{{ zuul.project.src_dir }}" =  /home/zuul-worker/src/github.com/ansible-network/network-engine
# "{{ ansible_path }}/test/runner/ansible-test"

####
- name: Show contents of "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
  find:
    paths: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
    file_type: directory
    recurse: yes
  register: find_results

- debug:
    var: find_results


###
# Copy files from local checkout on top of Ansible checkout
# This is only needed till ansible-test is updated

- name: Create modules/galaxy
  file:
    path: "{{ ansible_user_dir }}/{{ ansible_path }}/lib/ansible/modules/galaxy/"
    state: directory
  register: foo

- debug:
    var: foo

# with_* don't support remote so use name
- name: Copy modules
  copy:
    #src: "{{ item }}"
    src: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/library/get_config.py"
    dest: "{{ ansible_path }}/lib/ansible/modules/galaxy/"
    remote_src: yes
# with_fileglob:
#   - "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/library/*"
  ignore_errors: yes
  register: foo

- debug:
    var: foo

- name: Show contents of "{{ ansible_user_dir }}/{{ ansible_path }}/lib/ansible/modules/"
  find:
    paths: "{{ ansible_user_dir }}/{{ ansible_path }}/lib/ansible/modules/"
    file_type: directory
    recurse: yes
  register: find_results

- debug:
    var: find_results

###
# Run ansible-test
#

- name: Run ansible-test
  command: "{{ ansible_path }}/test/runner/ansible-test sanity --requirements --python {{ python_version }} --tox lib/ansible/modules/galaxy/"
