- name: Install Ansible
  pip:
    name: ansible
    #version: "2.5.0"
    extra_args: --user
    state: forcereinstall

- name: Install textfsm
  pip:
    name: textfsm
    extra_args: --user

- name: Run ansible-role-tests for network-engine
  command: "ansible-playbook --inventory ./inventory test.yml -vv"
  args:
    chdir: "{{ ansible_network_engine_path }}/tests/"
