---
ansible_path_query: "[?name=='ansible/ansible'].src_dir"
ansible_path: "{{ (zuul.projects.values() | list | json_query(ansible_path_query))[0] }}"
ansible_network_engine_path_query: "[?name=='ansible-network/network-engine-zuul'].src_dir"
ansible_network_engine_path: "{{ (zuul.projects.values() | list | json_query(ansible_network_engine_path_query))[0] }}"
